export const PRODUCTS_ACTIONS = {
	SET_PRODUCTS: 'SET_PRODUCTS',
	FETCH_PRODUCT_START: 'FETCH_PRODUCT_START',
	FETCH_PRODUCT_SUCCESS: 'FETCH_PRODUCT_SUCCESS',
	FETCH_PRODUCT_FAILED: 'FETCH_PRODUCT_FAILED',
};
